apiVersion: dax.vo/v1
kind: DockerCredentialSync
metadata:
  labels:
    app.kubernetes.io/name: docker-credential-sync
    app.kubernetes.io/managed-by: kustomize
  name: dockercredentialsync-sample
spec:
  sourceNamespace: dev
  sourceSecretName: registrypullsecret
  targetNamespacePrefix: "dev-"
  refreshIntervalSeconds: 3
